package org.marc4k.marc

const val SUBFIELD_DELIMITER_CHARACTER = '\u001F'

const val ESCAPE_CHARACTER = '\u001B'
const val SPACE_CHARACTER = '\u0020'

const val START_OF_STRING_CHARACTER = '\u0098'
const val STRING_TERMINATOR_CHARACTER = '\u009c'
const val ZERO_WIDTH_JOINER_CHARACTER = '\u200d'
const val ZERO_WIDTH_NON_JOINER_CHARACTER = '\u200c'
