package org.marc4k.converter.marc8

internal const val COMBINING_DOUBLE_INVERTED_BREVE_FIRST_HALF = '\u00EB'
internal const val COMBINING_DOUBLE_INVERTED_BREVE_SECOND_HALF = '\u00EC'
internal const val COMBINING_DOUBLE_TILDE_FIRST_HALF = '\u00FA'
internal const val COMBINING_DOUBLE_TILDE_SECOND_HALF = '\u00FB'
internal const val NON_SORT_BEGIN_CHARACTER = '\u0088'
internal const val NON_SORT_END_CHARACTER = '\u0089'
internal const val JOINER_CHARACTER = '\u008D'
internal const val NON_JOINER_CHARACTER = '\u008E'

internal const val SUBSCRIPT_GRAPHIC_CHARACTER = '\u0062'
internal const val GREEK_SYMBOLS_GRAPHIC_CHARACTER = '\u0067'
internal const val SUPERSCRIPT_GRAPHIC_CHARACTER = '\u0070'
internal const val ASCII_DEFAULT_GRAPHIC_CHARACTER = '\u0073'
internal const val BASIC_ARABIC_GRAPHIC_CHARACTER = '\u0033'
internal const val EXTENDED_ARABIC_GRAPHIC_CHARACTER = '\u0034'
internal const val BASIC_LATIN_GRAPHIC_CHARACTER = '\u0042'
internal const val EXTENDED_LATIN_GRAPHIC_CHARACTER = '\u0045'
internal const val BASIC_CYRILLIC_GRAPHIC_CHARACTER = '\u004E'
internal const val EXTENDED_CYRILLIC_GRAPHIC_CHARACTER = '\u0051'
internal const val BASIC_GREEK_GRAPHIC_CHARACTER = '\u0053'
internal const val BASIC_HEBREW_GRAPHIC_CHARACTER = '\u0032'
internal const val CJK_GRAPHIC_CHARACTER = '\u0031'

internal const val SINGLE_BYTE_G0_INTERMEDIATE = '\u0028'
internal const val SINGLE_BYTE_G0_ALTERNATE_INTERMEDIATE = '\u002C'
internal const val SINGLE_BYTE_G1_INTERMEDIATE = '\u0029'
internal const val SINGLE_BYTE_G1_ALTERNATE_INTERMEDIATE = '\u002D'

internal const val EXTENDED_LATIN_SECOND_INTERMEDIATE = '\u0021'

internal const val MULTI_BYTE_INTERMEDIATE = '\u0024'
internal const val MULTI_BYTE_G0_SECOND_INTERMEDIATE = '\u002C'
internal const val MULTI_BYTE_G1_SECOND_INTERMEDIATE = '\u0029'
internal const val MULTI_BYTE_G1_ALTERNATE_SECOND_INTERMEDIATE = '\u002D'

internal const val SUBSCRIPT_GRAPHIC_ISO_CODE = 0x62
internal const val GREEK_SYMBOLS_GRAPHIC_ISO_CODE = 0x67
internal const val SUPERSCRIPT_GRAPHIC_ISO_CODE = 0x70
internal const val BASIC_ARABIC_GRAPHIC_ISO_CODE = 0x33
internal const val EXTENDED_ARABIC_GRAPHIC_ISO_CODE = 0x34
internal const val BASIC_LATIN_GRAPHIC_ISO_CODE = 0x42
internal const val EXTENDED_LATIN_GRAPHIC_ISO_CODE = 0x45
internal const val BASIC_CYRILLIC_GRAPHIC_ISO_CODE = 0x4E
internal const val EXTENDED_CYRILLIC_GRAPHIC_ISO_CODE = 0x51
internal const val BASIC_GREEK_GRAPHIC_ISO_CODE = 0x53
internal const val BASIC_HEBREW_GRAPHIC_ISO_CODE = 0x32
internal const val CJK_GRAPHIC_ISO_CODE = 0x31

internal val C0_CONTROL_CHARACTER_RANGE = '\u0000'..'\u001F'
internal val C1_CONTROL_CHARACTER_RANGE = '\u0080'..'\u009F'